name: CI Pipeline

on:
  push:
    branches: [ master ]

jobs:
  Check-Code:
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 python3.8-venv -y
          git clone https://github.com/sam-don/mealplanner.git
          python3.8 -m venv mealplanner/venv
          mealplanner/venv/bin/pip3 install flake8 mypy
          
      - name: Flake8 Test
        run: |
          mealplanner/venv/bin/flake8 mealplanner/src/main.py

      - name: Mypy Test
        run: |
          mealplanner/venv/bin/mypy mealplanner/src/main.py
  Run-Tests:
    runs-on: ubuntu-latest
    steps:
      - name: Environment setup
        run: |
          sudo apt-get update
          sudo apt-get install python3.8 python3.8-venv -y
          git clone https://github.com/sam-don/mealplanner.git
          cd mealplanner
          python3.8 -m venv venv
          venv/bin/pip3 install -r requirements.txt

      - name: Run Tests
        run: |
          cd mealplanner/src
          venv/bin/python3.8 -m unittest discover tests/
